title: Michael Wooley # your name (or website title) here
logo: "/images/image0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S. in Aerospace Engineering 
  <br>
  University of Central Florida '20
  <br><br>
  Experience in project leadership, CAD, and CFD analysis
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
